<!DOCTYPE html>
<html>
    <head>
        <title>osu!Mirror - <?php echo $this->config->child->title ?></title>
        <link href="/mirror.css" rel="stylesheet" media="screen" type="text/css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript">
        function loadStats(){
            $('#stats').html('<div style="text-align: center;"><img src="/img/child-load.gif" alt="loading" style="vertical-align: top;" /></div>');
            setInterval("$('#stats').load('/index/stats');",3500);
        }
        $(document).ready(function(){
            $('#load-stats').click(loadStats);
        });
        </script>
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1><?php echo $this->config->child->title ?></h1>
                <a href="<?php echo $this->config->child->bannerUrl ?>" target="_self">
                <img src="<?php echo $this->config->mirror->basePath ?>/img/<?php echo $this->config->child->banner ?>" alt="logo" /></a>
            </header>
            <div class="box" id="stats">
                <div style="text-align: center;"><img src="/img/logo_med.png" id="load-stats" alt="logo" style="cursor: pointer; vertical-align: top;" /></div>
            </div>
            <footer>
                <a href="http://osu.yas-online.net">osu!Mirror</a> V2 &copy; by David Marner - <a href="http://development.yas-online.net/osumirror-child">Source</a> 
            </footer>
        </div>
    </body>
</html>